apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlredirection-deployment
  namespace: url-system
  labels:
    app: urlredirection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlredirection
  template:
    metadata:
      labels:
        app: urlredirection
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              # Hardcoded values verified from common-config ConfigMap.
              REDIS_HOST="redis.infra.svc.cluster.local"
              REDIS_PORT="6379"
              # Ensure you use the correct Kafka bootstrap service name
              KAFKA_HOST="kafka-bootstrap.infra.svc.cluster.local" 
              KAFKA_PORT="9092"

              # 1. Wait for Redis
              echo "Waiting for Redis DNS and port to be available: $REDIS_HOST:$REDIS_PORT"
              until nc -z $REDIS_HOST $REDIS_PORT; do
                echo "Redis ($REDIS_HOST:$REDIS_PORT) is unavailable - sleeping"
                sleep 2
              done
              echo "Redis is available! Continuing to Kafka check..."

              # 2. Wait for Kafka
              echo "Waiting for Kafka: $KAFKA_HOST:$KAFKA_PORT"
              until nc -z $KAFKA_HOST $KAFKA_PORT; do
                  echo "Kafka ($KAFKA_HOST:$KAFKA_PORT) is unavailable - sleeping"
                  sleep 5
              done
              echo "Kafka is available! Starting application container..."
      containers:
        - name: urlredirection
          image: neel0086/urlredirection:d2833e4
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: MONGODB_URI
            - name: SPRING_DATA_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MONGODB_DATABASE
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: REDIS_PORT
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: REDIS_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: BOOTSTRAP_SERVERS
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: POD_NAME
              valueFrom: 
                fieldRef:
                  fieldPath: metadata.name

