apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlredirection-deployment
  namespace: url-system
  labels:
    app: urlredirection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlredirection
  template:
    metadata:
      labels:
        app: urlredirection
    spec:
      containers:
        - name: urlredirection
          image: neel0086/urlredirection:92dd5aa
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: MONGODB_URI
            - name: SPRING_DATA_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MONGODB_DATABASE
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: REDIS_PORT
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: REDIS_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: BOOTSTRAP_SERVERS
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
