apiVersion: v1
kind: Service
metadata:
  name: urlredirection-service
  namespace: url-system
spec:
  selector:
    app: urlredirection
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
