name: CI/CD Pipeline

# Trigger on push or PR to master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from GitHub
    - name: Checkout source code
      uses: actions/checkout@v3

    # Step 2: Set up Java 17 with Eclipse Temurin
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'      # Eclipse Temurin is the OpenJDK distro
        java-version: '17'          # You’re using Java 17

    # Step 3: Cache Maven dependencies (optional but speeds up builds)
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build all microservices
    - name: Build all services
      run: |
        cd service-registry && mvn clean package -DskipTests && cd ..
        cd url-shortener && mvn clean package -DskipTests && cd ..
        cd url-redirection && mvn clean package -DskipTests && cd ..
        cd url-analytics && mvn clean package -DskipTests && cd ..
        cd api-gateway && mvn clean package -DskipTests && cd ..

    # Step 5: Build Docker images
    - name: Build Docker images
      run: |
        docker build -t urlshortener:latest ./url-shortener
        docker build -t urlredirection:latest ./url-redirection
        docker build -t urlanalytics:latest ./url-analytics
        docker build -t apigateway:latest ./api-gateway
        docker build -t serviceregistry:latest ./service-registry
