apiVersion: v1
kind: ConfigMap
metadata: 
  name: kafka-config
data:
  BROKER_ID: "1"
  CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
  CFG_LISTENERS: PLAINTEXT://:9092
  CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  ALLOW_PLAINTEXT_LISTENER: "yes"