# The error "Invalid value $(POD_NAME##*-) for configuration broker.id: Not a number of type INT"
# confirms that the shell substitution failed. The Kubernetes 'env' field does not execute shell scripts.
# FIX: The KAFKA_BROKER_ID environment variable is removed. The Bitnami Kafka image will automatically 
# derive the broker ID (0, 1, 2) from the StatefulSet's index when the ADVERTISED_LISTENERS are correctly set to the pod FQDN.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: infra
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: wait-for-zookeeper
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z zookeeper.infra.svc.cluster.local 2181; do
                echo "Waiting for ZooKeeper..."
                sleep 3
              done
      containers:
        - name: kafka
          image: bitnami/kafka:3.5
          ports:
            - containerPort: 9092
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
            # REMOVED: The problematic KAFKA_BROKER_ID variable has been removed.
            # The Bitnami entrypoint will now correctly calculate the Broker ID.

            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: CFG_ZOOKEEPER_CONNECT

            - name: KAFKA_CFG_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: CFG_LISTENERS

            # This advertised listener setting is correct for dynamic intra-cluster communication:
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://$(POD_NAME).kafka.infra.svc.cluster.local:9092

            - name: ALLOW_PLAINTEXT_LISTENER
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: ALLOW_PLAINTEXT_LISTENER

          volumeMounts:
            - name: kafka-storage
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi