apiVersion: v1
kind: Secret
metadata:
  name: urlshortener-secret
stringData:
  MONGODB_URI: "mongodb+srv://neelmehta0086:neel123@cluster0.m2wrdct.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  