---
apiVersion: v1
kind: Service
metadata:
  name: urlshortener-service
spec:
  selector:
    app: urlshortener
  type: ClusterIP
  ports:
    - protocol: TCP 
      port: 8080
      targetPort: 8080
