apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlanalytics-deployment
  namespace: url-system
  labels:
    app: urlanalytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlanalytics
  template:
    metadata:
      labels:
        app: urlanalytics
    spec:
      containers:
        - name: urlanalytics
          image: neel0086/urlanalytics:a42efdc
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: MONGODB_URI
            - name: SPRING_DATA_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MONGODB_DATABASE
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: BOOTSTRAP_SERVERS
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: REDIS_PORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
