apiVersion: v1
kind: Service
metadata:
  name: urlanalytics-service
  namespace: url-system
spec:
  selector:
    app: urlanalytics
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
