apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  type: NodePort
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30080  # Exposes it on localhost:30080
