server:
  port: 8081

spring:
  application:
    name: URL-REDIRECTION
  data:
    mongodb:
      uri: mongodb+srv://neelmehta0086:neel123@cluster0.m2wrdct.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: urlshortener
    redis:
      host: redis
      port: 6379
      password: neel123
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  analytics:
    topic: url-analytics-topic

  eureka:
    instance:
      prefer-ip-address: true
      hostname: localhost
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        default-zone: http://localhost:8761/eureka

